3_17:
	g++ 3_17.cpp -o 3_17.out
	./3_17.out < 3_17.txt
3_23:
	g++ 3_23.cpp -o 3_23.out
	./3_23.out
4_28:
	g++ 4_28.cpp -o 4_28.out
	./4_28.out
dose:
	g++ dose.cpp -o dose.out
	./dose.out < dose.txt
infl:
	g++ infl.cpp -o infl.out
	./infl.out < infl.txt
clean:
	rm *.out
