name: Hello World
on:
  push:
    braches: 
      -'3142Lab2/**'
jobs:
  HelloWorld:
    runs-on: ubuntu-latest
    steps: 
      - name: create prog
      - run: g++ hello.cpp
      - run: ./a.out
    
