name: Lab 10 Workflow
on: [push]
jobs:
  build:
  
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./lab10
      steps: 
      - uses: actions/checkout@master
      - name: Running lab10.cpp
        run: make lab10
