name: Lab 9 Workflow
on: [push]
jobs:
  build:
  
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./lab9
      steps: 
      - uses: actions/checkout@master
      - name: Running ex9.cpp
        run: make ex9
     
